ISSail/Controllers/ISMemberController.cs
/*
 * The ISMemberController class accesses and maintains records in the
 * Member table, and returns appropriate responses to user's requests
 * that allow them to view, create, edit or delete member records 
 * in the Sail database
 * 
 * Revision History
 *          Iryna Shynkevych 2018-11-25 : created
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ISSail.Models;

namespace ISSail.Controllers
{
    public class ISMemberController : Controller
    {
        private readonly SailContext _context;
        // the class constructor
        public ISMemberController(SailContext context)
        {
            _context = context;
        }

        // Index action displays all of the records in the Member table sorted by full name
        public async Task<IActionResult> Index()
        {
            var sailContext = _context.Member.Include(m => m.ProvinceCodeNavigation).OrderBy(m => m.FullName);
            return View(await sailContext.ToListAsync());
        }

        // Details action displays detailed information on a specific record selected based on the id
        // passed in parameters
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.ProvinceCodeNavigation)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // Setup Create action displays an empty form for the user to fill out in order to
        // create a new Member record
        public IActionResult Create()
        {
            return View();
        }

        // Postback Create action verifies if the data entered by the user is valid, adds it
        // to the database, and then saves the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberId,FullName,FirstName,LastName,SpouseFirstName,SpouseLastName,Street,City,ProvinceCode,PostalCode,HomePhone,Email,YearJoined,Comment,TaskExempt,UseCanadaPost")] Member member)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(member);
                    await _context.SaveChangesAsync();
                    TempData["message"] = $"Record for: {member.FullName} successfully added";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error: {ex.GetBaseException().Message}");
            }
            return View(member);
        }

        // Setup Edit action searches for the record based on its id, and, if successful, displays a form preloaded
        // wih its data for the user to edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(pc => pc.Name), "ProvinceCode", "Name", member.ProvinceCode);
            return View(member);
        }

        // Postback Edit action saves the changes made by user to the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberId,FullName,FirstName,LastName,SpouseFirstName,SpouseLastName,Street,City,ProvinceCode,PostalCode,HomePhone,Email,YearJoined,Comment,TaskExempt,UseCanadaPost")] Member member)
        {
            if (id != member.MemberId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                    TempData["message"] = $"Record updated for: {member.FullName}";
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (!MemberExists(member.MemberId))
                    {
                        ModelState.AddModelError("", $"Member under the name {member.FullName} is not on file");
                    }
                    else
                    {
                        ModelState.AddModelError("", $"Concurrency exception: {ex.GetBaseException().Message} ");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"update error: {ex.GetBaseException().Message}");
                }
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(pc => pc.Name), "ProvinceCode", "Name", member.ProvinceCode);
            return View(member);
        }

        // Setup Delete action searches for the record selected by user based on its id, and prompts user
        // to confirm their intention to delete it
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.ProvinceCodeNavigation)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // Postback Delete action removes the selected record and saves changes to the database
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var member = await _context.Member.FindAsync(id);
                _context.Member.Remove(member);
                await _context.SaveChangesAsync();
                TempData["message"] = $"Member '{member.FullName}' deleted from database";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = "Error on delete: " + ex.GetBaseException().Message;
            }
            return RedirectToAction("Delete", new { ID = id });
        }

        // Function MemberExists checks if a record already exists in the database based on its id
        private bool MemberExists(int id)
        {
            return _context.Member.Any(e => e.MemberId == id);
        }
    }
}

ISSail/Controllers/ISMembershipController.cs
/*
 * The ISMembershipController class accesses and maintains records in the
 * Membership table, and returns appropriate responses to user's requests
 * that allow them to view, create, edit or delete membership records 
 * for a specific member in the Sail database
 *
 * Revision History
 *          Iryna Shynkevych 2018-10-01 : created
 */
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using ISSail.Models;

namespace ISSail.Controllers
{
    public class ISMembershipController : Controller
    {
        private readonly SailContext _context;
        // the class constructor
        public ISMembershipController(SailContext context)
        {
            _context = context;
        }

        // Index action displays memberships for a specific member whose
        // id was passed in parameters or retrieved from a session variable
        public async Task<IActionResult> Index()
        {
            string memberId = "";
            string memberName = "";

            // look for the member id in the query string; if found, persist it 
            if (Request.Query["memberId"].Count != 0)
            {
                memberId = Request.Query["memberId"];
                HttpContext.Session.SetString("memberId", memberId);
            }
            //if not, look for it in a session variable
            else
            {
                if (HttpContext.Session.GetString(nameof(memberId)) != null)
                {
                    memberId = HttpContext.Session.GetString(nameof(memberId));
                }
            }
            //if not found there either, return to the ISMember Index view with a message
            // prompting the user to select the member whose memberships they wish to see
            if (memberId == "")
            {
                TempData["message"] = "Please, select a member to see their membership";
                return RedirectToAction("Index", "ISMember");
            }

            // look for member's name in the query string
            if (Request.Query["memberName"].Count != 0)
            {
                memberName = Request.Query["memberName"];
                HttpContext.Session.SetString("memberName", memberName);
            }
            // if not found, look for the member's name in the Members table based on memberId
            else
            {
                memberName = _context.Member.FirstOrDefault(m => m.MemberId == int.Parse(memberId)).FullName;
            }
            // persist member name
            HttpContext.Session.SetString("memberName", memberName);

            // save member name to the ViewBag
            ViewBag.MemberFullName = memberName;

            // display the membership information filtered by memberId and sorted by year
            var sailContext = _context.Membership.Include(m => m.Member)
                .Include(m => m.MembershipTypeNameNavigation)
                .Where(m => m.MemberId == int.Parse(memberId))
                .OrderByDescending(m => m.Year);

            return View(await sailContext.ToListAsync());
        }

        // Details action displays detailed information of a specific record selected based on 
        // its id passed as a parameter
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membership = await _context.Membership
                .Include(m => m.Member)
                .Include(m => m.MembershipTypeNameNavigation)
                .FirstOrDefaultAsync(m => m.MembershipId == id);
            if (membership == null)
            {
                return NotFound();
            }

            return View(membership);
        }

        // Setup Create action displays a form for user to fill out in order to create a new
        // membership
        public IActionResult Create()
        {
            // for a year drop-down (to restrict the choice down to years for which we have annual fees)
            ViewData["MembershipYear"] = new SelectList(_context.AnnualFeeStructure.OrderByDescending(m => m.Year), "Year", "Year");
            // for the membership type name drop-down sorted by name
            ViewData["MembershipTypeName"] = new SelectList(_context.MembershipType.OrderBy(m => m.MembershipTypeName), "MembershipTypeName", "MembershipTypeName");
            return View();
        }

        // Post-back Create action saving the new Membership record to the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MembershipId,MemberId,Year,MembershipTypeName,Fee,Comments,Paid")] Membership membership)
        {
            double annualFee = 0;
            double ratioToFull = 0;

            // if there are no errors in the membership data entered by user
            if (ModelState.IsValid)
            {
                // we retrieve the annual fee for the specified year from the AnnualFeeStructure table
                if (_context.AnnualFeeStructure
                    .SingleOrDefault(a => a.Year == membership.Year)
                    .AnnualFee != null)
                {
                    annualFee = (double)_context.AnnualFeeStructure
                        .SingleOrDefault(a => a.Year == membership.Year)
                        .AnnualFee;
                }
                // we retrieve the ratio to full for the specified membership type from the MembershipType table
                ratioToFull = _context.MembershipType.SingleOrDefault(a =>
                a.MembershipTypeName == membership.MembershipTypeName).RatioToFull;

                // we calculate the membership fee based on annual fee and ration to full
                membership.Fee = annualFee * ratioToFull;
                // and save the modified record to the database
                _context.Add(membership);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            // for a year drop-down (to restrict the choice down to years for which we have annual fees)
            ViewData["MembershipYear"] = new SelectList(_context.AnnualFeeStructure.OrderByDescending(m => m.Year), "Year", "Year");
            ViewData["MembershipTypeName"] = new SelectList(_context.MembershipType.OrderBy(m => m.MembershipTypeName), "MembershipTypeName", "MembershipTypeName", membership.MembershipTypeName);
            return View(membership);
        }

        // Setup Edit action displays the form for a specific membership record preloaded with its current
        // data for the user to edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            // to prevent the user to change records from previous years

            var membership = await _context.Membership.FindAsync(id);
            if (membership == null)
            {
                return NotFound();
            }
            if (membership.Year < DateTime.Now.Year)
            {
                TempData["message"] = "You cannot edit previous year's membership records!";
                return RedirectToAction("Index");
            }
            // for a year drop-down (to restrict the choice down to years for which we have annual fees)
            ViewData["MembershipYear"] = new SelectList(_context.AnnualFeeStructure.OrderByDescending(m => m.Year), "Year", "Year");
            ViewData["MembershipTypeName"] = new SelectList(_context.MembershipType.OrderBy(m => m.MembershipTypeName), "MembershipTypeName", "MembershipTypeName", membership.MembershipTypeName);
            return View(membership);
        }

        //Postback Edit action that saves the changes made by user into the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MembershipId,MemberId,Year,MembershipTypeName,Fee,Comments,Paid")] Membership membership)
        {
            if (id != membership.MembershipId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(membership);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembershipExists(membership.MembershipId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            // for a year drop-down (to restrict the choice down to years for which we have annual fees)
            ViewData["MembershipYear"] = new SelectList(_context.AnnualFeeStructure.OrderByDescending(m => m.Year), "Year", "Year");
            ViewData["MembershipTypeName"] = new SelectList(_context.MembershipType.OrderBy(m => m.MembershipTypeName), "MembershipTypeName", "MembershipTypeName", membership.MembershipTypeName);
            return View(membership);
        }

        // Setup Delete action displays details of a specific membership record retrieved based
        // on its id and prompts the user to confirm their intention to delete the record
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membership = await _context.Membership
                .Include(m => m.Member)
                .Include(m => m.MembershipTypeNameNavigation)

ISSail/Views/Shared/_Layout.cshtml
<!--
  The HTML code specifying the layout of the application's web pages
  Assignment 1
  Revision History
           Iryna Shynkevych 2018-09-14 : created
 */-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nautical Club</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" alt="Nautical club logo" width="50" class="left" />
                </a>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Nautical Club</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="ISAnnualFeeStructure" asp-action="Index">Annual Fees</a></li>
                    <li><a asp-area="" asp-controller="ISMember" asp-action="Index">Members</a></li>
                    <li><a asp-area="" asp-controller="ISMembership" asp-action="Index">Memberships</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <div class="tempdata">@TempData["message"]</div>
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-sm-6">
                    <br />
                    <p class="left">&copy;2018 - <a href="mailto:ishynkevych5158@conestogac.on.ca">Iryna Shynkevych</a></p>
                </div>
                <div class="col-sm-6">
                    <ul class="right nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>